export default {
  index: 'Introduction',
  installation: 'Installation',
  'getting-started': 'Getting Started',
  configuration: 'Configuration',
  client: 'Client & Lifecycle',
  events: 'Events',
  'sending-messages': 'Sending Messages',
  media: 'Media Processing',
  interactive: 'Interactive Messages',
  'rich-responses': 'Rich Responses (AIRich)',
  commands: 'Commands',
  automation: 'Broadcast & Schedule',
  presence: 'Presence',
  groups: 'Groups',
  community: 'Communities',
  newsletter: 'Newsletters (Channels)',
  privacy: 'Privacy & Blocking',
  storage: 'Storage Adapters',
  'error-handling': 'Error Handling',
  runtimes: 'Runtime Support',
  troubleshooting: 'Troubleshooting & FAQ',
  'api-reference': 'API Reference',
  skill: 'AI Skill',
}
