import type { AnyMessageContent } from 'baileys'
import { ZaileysBuilderError } from '../errors.js'
import type { PollOptions } from '../types.js'

const MIN_OPTIONS = 2
const MAX_OPTIONS = 12

/** Native poll content shape (rc13 `{ poll: PollMessageOptions }` branch). */
export type PollContent = {
  poll: { name: string; values: string[]; selectableCount: number }
}

/**
 * Build native poll content from a question and its options.
 *
 * rc13 decision: `{ poll: PollMessageOptions }` is the one interactive branch
 * still natively generated by `generateWAMessageContent`, which fans it out to
 * `pollCreationMessageV3` (single select) or `pollCreationMessage` (multi). No
 * proto hand-rolling required. `selectableCount` is `1` unless
 * `opts.multipleChoice` is set, in which case every option is selectable.
 *
 * @param question - poll title; must be non-empty.
 * @param options - 2..12 unique, non-empty option labels.
 * @param opts - `multipleChoice` widens `selectableCount` to `options.length`.
 * @throws ZaileysBuilderError `EMPTY_CONTENT` on a blank question,
 *   `INVALID_OPTIONS` on option count or duplicate violations.
 */
export const buildPollContent = (
  question: string,
  options: string[],
  opts?: PollOptions,
): AnyMessageContent => {
  if (typeof question !== 'string' || question.trim().length === 0) {
    throw new ZaileysBuilderError('EMPTY_CONTENT', 'poll() requires a non-empty question')
  }
  if (!Array.isArray(options) || options.length < MIN_OPTIONS) {
    throw new ZaileysBuilderError('INVALID_OPTIONS', `poll() requires a minimum of ${MIN_OPTIONS} options`)
  }
  if (options.length > MAX_OPTIONS) {
    throw new ZaileysBuilderError('INVALID_OPTIONS', `poll() accepts a maximum of ${MAX_OPTIONS} options`)
  }
  const seen = new Set<string>()
  for (const option of options) {
    if (typeof option !== 'string' || option.trim().length === 0) {
      throw new ZaileysBuilderError('INVALID_OPTIONS', 'poll options must be non-empty strings')
    }
    if (seen.has(option)) {
      throw new ZaileysBuilderError('INVALID_OPTIONS', `duplicate poll options: ${option}`)
    }
    seen.add(option)
  }

  const content: PollContent = {
    poll: {
      name: question,
      values: options,
      selectableCount: opts?.multipleChoice ? options.length : 1,
    },
  }
  return content as unknown as AnyMessageContent
}
